---
# I'm stupid and forgot to install mbstring
- hosts: ec2
  remote_user: ec2-user
  serial: 3
  tasks:
  - name: restart php-fpm
    command: sudo service php-fpm restart
  - name: restart NGINX
    command: sudo service nginx restart