---
# This playbook is for rolling out code to the servers.
- hosts: ec2
  remote_user: ec2-user
  serial: 3
  vars:
    destination: /srv/2000
  tasks:
  - name: Pull in latest 2000
    command: git pull
    args:
      chdir: "{{ destination }}"

  - name: Bower Install (not Bowser)
    command: bower install
    args:
      chdir: "{{ destination }}"

  - name: NPM Install/Update
    npm: path={{ destination }}

  - name: Grunt Deploy
    command: grunt deploy
    args:
      chdir: "{{ destination }}"