---
# This playbook is for rolling out code to the servers.
- hosts: ec2
  remote_user: ec2-user
  serial: 2
  vars:
    destination: /srv/2000
    project_repo: 
  tasks:
  - name: Pull in latest 2000
    git:
     repo=ssh://git@github.com:TwoThousandTimes/2000.git
     dest=/srv/2000
     accept_hostkey=yes
     force=yes

  - name: Bower Install (not Bowser)
    command: bower install
    args:
      chdir: "{{ destination }}"

  - name: NPM Install/Update
    npm: path={{ destination }}

  - name: Grunt Deploy
    command: grunt deploy
    args:
      chdir: "{{ destination }}"